// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANraD7bqm3mDM9LpPjZRehyLAK9DT7CoE',
    appId: '1:748398520140:web:3c9a5295872b3c695711e9',
    messagingSenderId: '748398520140',
    projectId: 'rubrik-daddf',
    authDomain: 'rubrik-daddf.firebaseapp.com',
    storageBucket: 'rubrik-daddf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNRbdahGRM04gxb9OMryLN0FFIl6KborI',
    appId: '1:748398520140:android:03f47d8c610101a05711e9',
    messagingSenderId: '748398520140',
    projectId: 'rubrik-daddf',
    storageBucket: 'rubrik-daddf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPrAJ7zaNqG78FKGwqCrGIuad4dVkDuIY',
    appId: '1:748398520140:ios:bd432e25129d392c5711e9',
    messagingSenderId: '748398520140',
    projectId: 'rubrik-daddf',
    storageBucket: 'rubrik-daddf.firebasestorage.app',
    iosBundleId: 'com.example.rubrik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPrAJ7zaNqG78FKGwqCrGIuad4dVkDuIY',
    appId: '1:748398520140:ios:bd432e25129d392c5711e9',
    messagingSenderId: '748398520140',
    projectId: 'rubrik-daddf',
    storageBucket: 'rubrik-daddf.firebasestorage.app',
    iosBundleId: 'com.example.rubrik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANraD7bqm3mDM9LpPjZRehyLAK9DT7CoE',
    appId: '1:748398520140:web:15029493dc86fd025711e9',
    messagingSenderId: '748398520140',
    projectId: 'rubrik-daddf',
    authDomain: 'rubrik-daddf.firebaseapp.com',
    storageBucket: 'rubrik-daddf.firebasestorage.app',
  );
}
